#!/usr/bin/env python3
"""
Quiz import/export lifecycle test.

Covers three endpoints that had zero regression coverage:
  GET  /quizzes/import/template      — download blank Excel template
  POST /quizzes/import/validate      — parse + validate an uploaded .xlsx
  POST /quizzes/import/export-draft  — generate .xlsx from frontend draft JSON
  POST /quizzes/import/finalize      — create quiz from validated import data

Test strategy (no real Excel writing needed):
  1. Template download works and returns xlsx content-type.
  2. Uploading a non-xlsx file is rejected with 400.
  3. Uploading the template itself (blank, no questions) returns validation
     results without 500.
  4. export-draft with a minimal draft returns xlsx bytes.
  5. finalize with canImport=false returns 400.
  6. Full round-trip: export a draft → validate → finalize → quiz created.
"""
import io
import os
import sys
import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

BASE_URL = os.getenv("BASE_URL", "https://test.swaya.me/api/v1").rstrip("/")
EMAIL = os.getenv("HOST_EMAIL", "demo@swaya.me")
PASSWORD = os.getenv("HOST_PASSWORD", "Demo1234")

XLSX_CONTENT_TYPE = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

MINIMAL_DRAFT = {
    "title": "RegTest Import Quiz",
    "description": "auto-generated by regression",
    "quiz_type": "quiz",
    "duration_minutes": None,
    "questions": [
        {
            "text": "What is 1 + 1?",
            "question_type": "mcq",
            "options": ["1", "2", "3", "4"],
            "correct_answer_index": 1,
            "points": 100,
            "max_time_seconds": 20,
        }
    ]
}


def fail(msg: str):
    print(f"FAIL: {msg}")
    sys.exit(1)


def check(cond: bool, msg: str):
    if not cond:
        fail(msg)


def main():
    s = requests.Session()
    s.verify = False

    # Login
    r = s.post(f"{BASE_URL}/auth/login",
               json={"email": EMAIL, "password": PASSWORD}, timeout=20)
    check(r.status_code == 200, f"login failed: {r.status_code}")
    s.headers["Authorization"] = f"Bearer {r.json()['access_token']}"
    print("OK: login")

    # 1. GET /quizzes/import/template → xlsx file
    r = s.get(f"{BASE_URL}/quizzes/import/template", timeout=20)
    check(r.status_code == 200, f"template download failed: {r.status_code} {r.text[:200]}")
    check(
        XLSX_CONTENT_TYPE in r.headers.get("content-type", ""),
        f"template not xlsx: content-type={r.headers.get('content-type')}"
    )
    template_bytes = r.content
    check(len(template_bytes) > 100, "template file is suspiciously small")
    print(f"OK: template download  size={len(template_bytes)}B")

    # 2. POST /quizzes/import/validate with wrong file type → 400
    r = s.post(
        f"{BASE_URL}/quizzes/import/validate",
        files={"file": ("test.txt", io.BytesIO(b"not an excel file"), "text/plain")},
        timeout=20,
    )
    check(r.status_code == 400, f"wrong-type upload should be 400, got {r.status_code}")
    print("OK: non-xlsx upload correctly rejected with 400")

    # 3. POST /quizzes/import/validate with the blank template → not 500
    r = s.post(
        f"{BASE_URL}/quizzes/import/validate",
        files={"file": ("template.xlsx", io.BytesIO(template_bytes), XLSX_CONTENT_TYPE)},
        timeout=20,
    )
    check(
        r.status_code != 500,
        f"validate with blank template returned 500: {r.text[:300]}"
    )
    check(
        r.status_code in (200, 400),
        f"validate returned unexpected {r.status_code}"
    )
    print(f"OK: blank template validation  status={r.status_code} (no 500)")

    # 4. POST /quizzes/import/export-draft with minimal draft → xlsx bytes
    r = s.post(f"{BASE_URL}/quizzes/import/export-draft", json=MINIMAL_DRAFT, timeout=20)
    check(r.status_code == 200, f"export-draft failed: {r.status_code} {r.text[:200]}")
    check(
        XLSX_CONTENT_TYPE in r.headers.get("content-type", ""),
        f"export-draft not xlsx: content-type={r.headers.get('content-type')}"
    )
    draft_xlsx = r.content
    check(len(draft_xlsx) > 100, "exported draft xlsx is suspiciously small")
    print(f"OK: export-draft  size={len(draft_xlsx)}B")

    # 5. POST /quizzes/import/finalize with canImport=false → 400
    r = s.post(f"{BASE_URL}/quizzes/import/finalize",
               json={"canImport": False, "questions": []}, timeout=20)
    check(r.status_code == 400, f"finalize with canImport=false should be 400, got {r.status_code}")
    print("OK: finalize with canImport=false correctly rejected with 400")

    # 6. Full round-trip: validate the exported draft, then finalize.
    r = s.post(
        f"{BASE_URL}/quizzes/import/validate",
        files={"file": ("draft.xlsx", io.BytesIO(draft_xlsx), XLSX_CONTENT_TYPE)},
        timeout=20,
    )
    check(r.status_code == 200, f"validate exported draft failed: {r.status_code} {r.text[:300]}")
    validation = r.json()
    can_import = validation.get("canImport", False)
    print(f"OK: validate exported draft  canImport={can_import}")

    created_quiz_id = None
    if can_import:
        r = s.post(f"{BASE_URL}/quizzes/import/finalize", json=validation, timeout=20)
        check(r.status_code in (200, 201), f"finalize failed: {r.status_code} {r.text[:300]}")
        created_quiz_id = r.json().get("id")
        check(bool(created_quiz_id), "finalize returned no quiz id")
        print(f"OK: finalize created quiz  id={created_quiz_id}")
    else:
        print(f"SKIP: finalize skipped (exported draft not importable: {validation.get('errors', [])})")

    # Cleanup
    if created_quiz_id:
        s.delete(f"{BASE_URL}/quizzes/{created_quiz_id}", timeout=20)
        print("OK: cleanup quiz")

    print("\nOK: quiz_import_export — all checks passed")


if __name__ == "__main__":
    main()
