"""add_email_verification

Revision ID: 23f58c7f5b8a
Revises: z1a2b3c4d5e6
Create Date: 2026-03-08 02:14:44.853058

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '23f58c7f5b8a'
down_revision: Union[str, None] = 'z1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Because MySQL does not support transactional DDL, earlier failed 
    # runs may have successfully added the columns before crashing. 
    # We use the inspector to make this idempotent.
    bind = op.get_bind()
    insp = sa.inspect(bind)
    columns = [col['name'] for col in insp.get_columns('users')]
    
    if 'is_email_verified' not in columns:
        op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), server_default='0', nullable=False))
    if 'email_verification_token' not in columns:
        op.add_column('users', sa.Column('email_verification_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
